steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=raphaelsolarski --password=$$PASSWORD ghcr.io']
    secretEnv: ['PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t ghcr.io/raphaelsolarski/ukrainski-dom-forms/housing-app:${SHORT_SHA} .']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push ghcr.io/raphaelsolarski/ukrainski-dom-forms/housing-app:${SHORT_SHA}']
availableSecrets:
  secretManager:
    - versionName: projects/954990661549/secrets/github-container-registry-key/versions/1
      env: 'PASSWORD'
