# Generated by Django 3.2.12 on 2025-04-02 21:35

from django.db import migrations, models
import house_of_refuge.main.models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_housing_resource_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingresource',
            name='newsletter_agreement',
            field=models.BooleanField(default=False, verbose_name='Newsletter agreement'),
        ),
        migrations.AddField(
            model_name='submission',
            name='newsletter_agreement',
            field=models.BooleanField(default=False, verbose_name='Newsletter agreement'),
        ),
    ]
