# Generated by Django 3.2.12 on 2023-03-20 12:53

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_housing_resource_update'),
    ]

    operations = [
        migrations.RunSQL("""INSERT INTO main_voivodeship ("name", "namePl", "nameEN") VALUES
            ('all', 'wszystkie', 'all')
        """),
    ]
